source ~/.vim/vundle-loader.vim

set t_Co=256

set number
syntax on
set hlsearch "highlight search

if has('gui_running')
	colorscheme base16-tomorrow-night
else " the base16 version needs the terminal's theme to be tomorrow as well, which is not my case so I have to fallback to the original version
	colorscheme Tomorrow-Night
	hi Normal ctermbg=NONE " Override theme's background to terminal's default. Useful when it is transparent
endif

highlight ExtraWhitespace ctermbg=darkred guibg=darkred "show trailing whitespace
autocmd Syntax * syn match ExtraWhitespace /\s\+\%#\@<!$/ "except when typing at the end of a line

fun! ShowConsecutiveSpaces()
    "except for these filetypes
    if &ft =~ 'text\|sql\|asm68k'
        return
    endif
	syn match SpaceIndent / \{2,\}/
endfun
highlight SpaceIndent ctermbg=darkgrey guibg=darkgrey "show two or more consecutive spaces
autocmd Syntax * call ShowConsecutiveSpaces()

if has('mouse')
	if &term =~# "^screen"
		set mouse=a "all
	else
		set mouse=ar "all + middle click copy/paste
	endif
endif

set shiftwidth=4 "for > command
set tabstop=4 "hard tabs are 4 spaces wide
set noexpandtab "always insert tabs with the tab key

"makes more sense on colemak
noremap j h
noremap h k
noremap k j

nnoremap <silent> <C-t> :%s/\ \ \ \ /\t/g<CR>
nnoremap <silent> <C-l> :nohl<CR><C-l>

set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

set autoread

au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif "remember position in file
set noswapfile

set clipboard=unnamedplus "share vim and the computer's clipboard

au FileType gitcommit set tw=0
autocmd FileType markdown,text,tex setlocal spell
au BufRead,BufNewFile *.jake set filetype=javascript
